archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
before:
  hooks:
    - go mod tidy
builds:
  - binary: "{{ .ProjectName }}_v{{ .Version }}"
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
    ldflags:
      - "-s -w -X main.commit={{.Commit}} -X main.version={{.Version}}"
    mod_timestamp: "{{ .CommitTimestamp }}"
changelog:
  skip: true
checksum:
  algorithm: sha256
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
signs:
  - args:
      - "--batch"
      - "--detach-sign"
      - "${artifact}"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
    artifacts: checksum
